AWSTemplateFormatVersion: '2010-09-09'
Description: flows aws athena
Resources:
  queryFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: mesh-plugin-prod-artifacts
        S3Key: 21801b5d0377850f98e677031cb8a679
      Handler: main.handler
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      Runtime: nodejs8.10
      Timeout: 300
  queryLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${queryFunction}
      RetentionInDays: 7
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: LambdaRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: LambdaRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
            - Fn::GetAtt:
              - queryFunction
              - Arn
Outputs:
  queryFunction:
    Description: query
    Value:
      Fn::GetAtt:
      - queryFunction
      - Arn
  queryRole:
    Description: query
    Value:
      Fn::GetAtt:
      - InvokeRole
      - Arn
